name: 'review'
on:
  # onl run this workflow on pull request events
  pull_request

jobs:
  review_app:
    runs-on: ubuntu-latest
    # only run when a pull request is opened
    if: github.event_name == 'pull_request' && github.event.action == 'opened'
    steps:
      - name: Cloning repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Dokku SSH key
        uses: webfactory/ssh-agent@v0.6.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Create review app and database
        run: |
          ssh -o StrictHostKeyChecking=no dokku@dokku.aldazosa.net apps:create dai-ichi-${{ github.event.pull_request.number }}
          ssh -o StrictHostKeyChecking=no dokku@dokku.aldazosa.net postgres:create dai-ichi-${{ github.event.pull_request.number }}-db
          ssh -o StrictHostKeyChecking=no dokku@dokku.aldazosa.net postgres:link dai-ichi-${{ github.event.pull_request.number }}-db dai-ichi-${{ github.event.pull_request.number }}

      - name: Push to dokku
        run: |
          git remote add dokku dokku@dokku.aldazosa.net:dai-ichi-${{ github.event.pull_request.number }}
          git checkout ${{ github.event.pull_request.head.ref }}
          git push dokku ${{ github.event.pull_request.head.ref }}:master
